name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    env:
      NUXT_PUBLIC_MAP_TILER_KEY: ${{ vars.NUXT_PUBLIC_MAP_TILER_KEY }}
      NUXT_PUBLIC_GOOGLE_MAP_TILES_API_KEY: ${{ vars.NUXT_PUBLIC_GOOGLE_MAP_TILES_API_KEY }}
      NUXT_PUBLIC_CLOCKWORK_API_KEY: ${{ vars.NUXT_PUBLIC_CLOCKWORK_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: pnpm install
      - name: Setup playground
        run: pnpm run dev:prepare
      - name: Build playground
        run: NUXT_APP_BASE_URL=/nuxt-maplibre/demo pnpm run demo:generate -- --preset github_pages
      - name: Build with VitePress
        run: VITE_BASE_URL=/nuxt-maplibre/ pnpm run docs:build
      - name: Make demo directory
        run: mkdir -p docs/.vitepress/dist/demo
      - name: Copy playground to docs
        run: cp -r playground/.output/public/* docs/.vitepress/dist/demo
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
