name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - run: pnpm install
      - name: Lint with ESLint
        run: pnpm run lint
      - name: Prepare testing with the playground
        run: pnpm run dev:prepare
      - name: Test package
        run: pnpm run test
      - name: Prepack
        run: pnpm run prepack
      - name: Configuring Git
        run: git config --global user.name "GitHub CD bot" && git config --global user.email "github-cd-bot@users.noreply.github.com"
      - name: Update package version
        run: pnpm --no-git-tag-version version ${GITHUB_REF_NAME#v}
      - name: Publish package to NPM
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push changes to GitHub
        run: git commit -am "Release ${GITHUB_REF_NAME}" && git push origin HEAD:main
