name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'test/**'
      - 'playground/**'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'test/**'
      - 'playground/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - name: Lint with ESLint
        run: pnpm run lint
      - name: Prepare testing with the playground
        run: pnpm run dev:prepare
      - name: Test package
        run: pnpm run test
